[project]
name = "air-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "air>=0.16.0",
    "air-markdown>=0.1.0",
    "beautifulsoup4>=4.13.4",
    "fastapi[standard]>=0.116.1",
    "uvicorn>=0.35.0",
]
